// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/app'
import { Route as IndexImport } from './routes/index'
import { Route as AppPostsIndexImport } from './routes/app/posts/index'
import { Route as AppPostsPostIdIndexImport } from './routes/app/posts/$postId/index'

// Create/Update Routes

const AppRoute = AppImport.update({
  path: '/app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppPostsIndexRoute = AppPostsIndexImport.update({
  path: '/app/posts/',
  getParentRoute: () => rootRoute,
} as any)

const AppPostsPostIdIndexRoute = AppPostsPostIdIndexImport.update({
  path: '/app/posts/$postId/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/posts/': {
      preLoaderRoute: typeof AppPostsIndexImport
      parentRoute: typeof rootRoute
    }
    '/app/posts/$postId/': {
      preLoaderRoute: typeof AppPostsPostIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/app': {
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppPostsIndexRoute,
  AppPostsPostIdIndexRoute,
  AppRoute,
])
